### ISSUE TITLE
Coevolution of Faulttree and CTMC

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#132]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | coevolve FaultTree2CTMC |
| **to** | hold them consistent |

**Done When:**
- [x] Create Projects, Features, Extensions, TransformationManager (handle OneWay) #241
- [x] Create Henshin Rules FaultTree2CTMC  #242

**Comment by equiFX** [comment]
feature implemented, but transformation is still incomplete. ref #435
