### ISSUE TITLE
Create a new Co-Evolved Project

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#2]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | create a new evolution project with a good folder structure |
| **to** | handle all models of the project |

References:
- [ ] Research: Eclipse plugin development #28

**Comment by verenya** [comment]
This should work now.  It's possible to create new projects and added resources are shown correctly. Just the right-click-menu is missing so it's not possible to add content  in our navigator at the moment
