### ISSUE TITLE
Create safety model (Fault Tree)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#23]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | create a fault tree |
| **to** | model the safety of my system |

**Done When:**
- [ ] Define a wizard to create the model file
- [ ] Make the model editable with text editor
- [ ] Add evolution rules

**Comment by timsanwald** [comment]
Maybe there is an interesting fault tree meta model:
http://www.iste.uni-stuttgart.de/en/rss/projects/ensure/consistencysaft.html

**Comment by maborjan** [comment]
model commited in branch #13
