### ISSUE TITLE
Prepare project for publication

### ISSUE THREAD

**Issue by philippniethammer** [CoWolf/CoWolf#303]
CoWolf is going to go public after the end of the project. For this, some things have to be done, first.

The following list is just a collection of points that came to my mind. Part of this ticket is to think about what has to be done.
- [x] Add licensing information wherever needed (each plugin project?)
- [x] Add information about the project (README?)
- [x] Make sure all plugins have the correct name and organisation information
- [x] Add descriptions to the feature plugins

**Comment by timsanwald** [comment]
Also add descriptions to the feature plugins

**Comment by philippniethammer** [comment]
@ReneTrefft Status?
