### ISSUE TITLE
Creation of modeling projects

### ISSUE THREAD

**Issue by verenya** [CoWolf/CoWolf#304]
To have a good usability it is necessary that the user does not have to do the connection between viewpoint and models

Finished when:
- [x] Modeling project nature is attached to cowolf projects
- [x] programmatic creation of viewpoints
- [x] filter for representation files
- [x] extension of sirius classes so that models in subfolders are found

**Comment by philippniethammer** [comment]
Duplicate of #262. Copied description there.
