### ISSUE TITLE
Correct Merge

### ISSUE THREAD

**Issue by philippniethammer** [CoWolf/CoWolf#353]
9fa0c77 and bb660bf5d26b2e70c9ad4a7375169eb7d792f191 removed some manual changes in FaultTree model that were not marked correctly. Go through diffs and redo them.

**Comment by maborjan** [comment]
Which manual changes are these exactly?

**Comment by philippniethammer** [comment]
Well, that's the fun part of this task. Scanned over both, found parts in both. E.g. FaultTreeModelWizard.java ll. 290ff.

**Comment by maborjan** [comment]
After code revision, the only affected file was FaultTreeModelWizard.java (method performFinish())
- Added the not key word so that this doesn't happen again.
- Validate with @verenya that there is no further damages

**Comment by philippniethammer** [comment]
FaultTreeItemProvider.java in 9fa0c7732daa0f9f22e84d026ca18e3adfec9435 was a manual change, too, I think, but anyway...
