### ISSUE TITLE
StateMachine -> DTMC: Check what happens with recursive containers in SM.

### ISSUE THREAD

**Issue by philippniethammer** [CoWolf/CoWolf#358]

**Comment by jonasscheurich** [comment]
@jonasscheurich

**Comment by jonasscheurich** [comment]
**Test1:**

Pre: 
- _one statemachine(name=random)_
- _two states, transition and a composite state_

Action:
_Create State c_1, State c_2, Transition c_1 -> c_2 in a CompsiteState_
-  Called recognitionrules
  - CREATE_Transition_IN_State_(internalTransitions)
  - CREATE_State_IN_CompositeState_(subVertexes)
  - CREATE_State_IN_CompositeState_(subVertexes)

Action Result:
No rules are executed, no changes in DTMC

**Result**
- **States and transitions containerd in CompositeStates are ignored**

**Comment by jonasscheurich** [comment]
**Test2:**

Pre:
.. based on Test1.

Action:
_second statemachine (name=random)_
_Create State start_SUB, State end_SUB, Transition start_SUB-> end_SUBin a CompsiteState_

Action Result:
two additional states with a transtion between are created

**Comment by jonasscheurich** [comment]
**Test3:**

Pre:
.. based on Test2.

Action
- DO in a state to the substatemachine

Result:

```
=== (6) UNDONE UNIT 'CreatedActionInSC' [TRUE] ===

Graph size: 619 nodes, 2791 edges

Assignment for unit 'CreatedActionInSC':
- parameter 'actionId' => '_037LEkP4EeSxfJKDsv9bkw'

Result assignment for unit 'CreatedActionInSC':
- parameter 'actionId' => '_037LEkP4EeSxfJKDsv9bkw'
- parameter 'stateId' => '_MN2sgUP1EeSxfJKDsv9bkw'

=== (7) EXECUTED UNIT 'CreatedActionInSC' [FALSE] ===
```

The Rule is not executed, because the intialStatemachine isn't set.

**Comment by jonasscheurich** [comment]
**Test4:**

Pre:
- one SM as initalSM
- two nodes with a transition

Action:
- Create a DO action in the second node

Action Result:
- Transition from node two to node one

**Result:**
- **No endless loop execution of transformations, because the rules are depended to the finite SymmetricDifference via the mapping file.**

**Comment by jonasscheurich** [comment]
**Test5**

Pre:
- based on Test4
- second SM with two nodes and a transition
- DO action from the second state in inital SM to the second SM

Action:
- DO action from second state in second SM to the inital SM

Action Result:
- **Transition from the last node in DTMC to the first node in DTMC**

**Comment by jonasscheurich** [comment]
Summary:
- no endless execution
- transitions traced to a DO action are valid in the DTMC context.

-> false positive bug report.
