### ISSUE TITLE
Bidirectional Co-Evolution creates duplicates

### ISSUE THREAD

**Issue by DavidSteinhart** [CoWolf/CoWolf#389]
Example:
Create Dtmc
Create Ctmc
Add State A to DTMC, mark as start state
Co-Evolve Dtmc -> Ctmc

Add State B to Ctmc
Co-Evolve Ctmc -> Dtmc
Co-Evolve Ctmc -> Dtmc again

State B is inserted twice

Also works for any other changes or transformations, e.g. State Chart <-> DTMC

**Comment by philippniethammer** [comment]
Can't reproduce.

**Comment by timsanwald** [comment]
Can't reproduce
