### ISSUE TITLE
Limit Create Representation to model files

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#420]
Limitate the menu entry of "Create Representation" to be visible only when selecting of model/models.
Otherwise we have a menu entry like SERGe...

**Comment by verenya** [comment]
Actually this should be done by the Property tester. Is this a bug?

**Comment by timsanwald** [comment]
Which property tester? By me it's showed on project and all other files

**Comment by verenya** [comment]
Works for me on branch 272 :) In ui.navigator there is a GraphicalEditorTest connected to the menu entry. Perhaps something went lost during the merge into the master

**Comment by timsanwald** [comment]
The method is disabled, but it is visible at all files for me even on branch 272

**Comment by verenya** [comment]
Sorry, I misunderstood that. Is in work
