### ISSUE TITLE
Remove dependency in ui.navigator to model.sequence_diagram

### ISSUE THREAD

**Issue by renetrefft** [CoWolf/CoWolf#421]
At the moment the class `CreateRepresentationAndViewpointHandler` in ui.navigator imports a class of the sequence diagram model. 

This class should be moved to another project, e.g. ui.model.sequence_diagram, if it's necessary for sequence diagrams only.

**Comment by verenya** [comment]
The CreateRepresentationAndViewpointHandler is necessary for all graphical editors. It imports the Interaction element of the sequence Diagrams because sequence diagrams need a special root element

**Comment by verenya** [comment]
Possible solution: Not to check for Sequence diagram interaction but for uml interaction as the sequence diagram interaction extends the uml interaction and we already have the uml dependency

**Comment by timsanwald** [comment]
Wouldn't it be possible to define an extension point to deal with this?

**Comment by verenya** [comment]
Not an extension point but perhaps a method in the model managers to return the root element  from a resource
