### ISSUE TITLE
LQN Constructor: Solver parameters must be added

### ISSUE THREAD

**Issue by maborjan** [CoWolf/CoWolf#460]
The Solver Params element must be added as soon as a new LQN model is created.

The mandatory values are:
- Conv Val (default value=1)
- It Limit (default value=50)
- Print int (default value=0)
- Underrelax coef (default value=1)

Anyway, the default values are defined in the metamodel. One can take them from there.

**Comment by jonasscheurich** [comment]
@jonasscheurich
