### ISSUE TITLE
Recognition rules of CTMC don't work

### ISSUE THREAD

**Issue by zimmerml** [CoWolf/CoWolf#479]
Added states or transitions in a ctmc are not shown as change sets in the differences view. Only the technical changes are shown.

**Comment by philippniethammer** [comment]
Same for DTMC!

**Comment by philippniethammer** [comment]
Potentially same as #481 #489

**Comment by timsanwald** [comment]
shouldn't be the same, the lifting is done in every case not just baseversion to another
