### ISSUE TITLE
Statemachine -> DTMC does not set Prob properly, overwrites existing values

### ISSUE THREAD

**Issue by DavidSteinhart** [CoWolf/CoWolf#483]
Create Statemachine and DTMC file
Build simple Statemachine
Co-Evolve to DTMC
Change probs in DTMC
Change Statemachine, co-evolve to DTMC again
All probs in DTMC are 0.0 again

**Comment by philippniethammer** [comment]
Actually these are two tasks, first the bug with prob = 0, second an enhancement with meaningful initialization. For the latter, I think it's not good, because the user can't find the new transitions easily then.
